require 'hippocampome/article_row_loader'
require 'hippocampome/attachment_row_loader'
require 'hippocampome/epdata_row_collapser'
require 'hippocampome/epdata_row_processor'
require 'hippocampome/epdata_statement_processor'
require 'hippocampome/epdata_statement_loader'
require 'hippocampome/figure_row_loader'
require 'hippocampome/fragment_matcher'
require 'hippocampome/hc_main_statement_loader'
require 'hippocampome/hc_main_row_processor'
require 'hippocampome/marker_fragment_row_loader'
require 'hippocampome/marker_fragment_row_processor'
require 'hippocampome/markerdata_statement_loader'
require 'hippocampome/markerdata_statement_processor'
require 'hippocampome/markerdata_row_processor'
require 'hippocampome/medline_record'
require 'hippocampome/morph_fragment_row_loader'
require 'hippocampome/morph_fragment_row_processor'
require 'hippocampome/packet_notes_row_loader'
require 'hippocampome/port_data'
require 'hippocampome/processors'
require 'hippocampome/soma_statement_processor'
require 'hippocampome/type_mapping_processor'
require 'hippocampome/type_row_loader'
require 'hippocampome/epdata_record_validator'
require 'hippocampome/marker_evidence_link_row_processor'
require 'hippocampome/marker_evidence_link_statement_processor'
require 'hippocampome/marker_evidence_link_statement_loader'
require 'hippocampome/type_matcher'
require 'hippocampome/known_connections_row_loader'
require 'hippocampome/known_connections_row_processor'
require 'hippocampome/morph_property_patcher'
require 'hippocampome/one_type_morph_property_patcher'

require 'extensions/string'

module Hippocampome

end
